is2_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html"), name='Home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('menu/',include('menu_principal.urls')),
    path('proyecto/', include('proyecto.urls')),
    path('sin_acceso/', TemplateView.as_view(template_name='acceso_pendiente.html'), name='Acceso Pendiente'),
    # Login
    path('usuarios/', include('login_social.urls')),
    # Front End
    path('app/', include('frontend.urls')),
]

item/urls.py
from django.urls import path
from . import ajax

urlpatterns = [
    path('crearTipo/', ajax.ajax_crear_tipo_item, name='Crear tipo de item'),
    path('listarTipo/', ajax.ajax_listar_tipo_item, name='Listar tipo de item'),
    path('verificarTipo/', ajax.ajax_verificar_tipo_item_modificable, name='Verificar tipo de item'),
    path('eliminarTipo/', ajax.ajax_eliminar_tipo_item, name='Eliminar tipo de item'),
    path('editarTipo/', ajax.ajax_editar_tipo_item, name='Editar tipo de item'),
    path('importarTipo/', ajax.ajax_importar_tipo, name='AJAX Importar Tipo'),
    path('obtenerTipo/', ajax.ajax_obtener_tipo_de_item, name='AJAX Obtener tipo de item'),
    path('obtenerTipos/', ajax.ajax_obtener_tipos_de_item_de_proyecto, name='AJAX Obtener tipos de item de proyecto'),
    # AJAX Item
    path('crearItem/', ajax.ajax_crear_item_en_fase, name='AJAX Crear Item en Fase'),
    path('modificarItem/', ajax.ajax_modificar_item_en_fase, name='AJAX Modificar Item en Fase'),
    path('desactivarItem/', ajax.ajax_desactivar_item_en_fase, name='AJAX Desactivar Item en Fase'),
    path('obtenerItemsProyecto/', ajax.ajax_obtener_items_de_proyecto, name='AJAX Obtener Items del Proyecto'),
    path('relacionarItem/', ajax.ajax_relacionar_item, name='AJAX Relacionar items de proyecto'),
    path('desrelacionarItem/', ajax.ajax_desrelacionar_item, name='AJAX Desrelacionar items de proyecto'),
    path('solicitudAprobacionItem/', ajax.ajax_solicitud_aprobacion_item,
         name='AJAX Solicitud Aprobar items de proyecto'),
    path('cancelarsolicitudAprobacionItem/', ajax.ajax_cancelar_solicitud_aprobacion_item,
         name='AJAX Cancelar Solicitud Aprobar items de proyecto'),
    path('AprobarItem/', ajax.ajax_aprobar_item, name='AJAX Aprobar items de proyecto'),
    path('DesaprobarItem/', ajax.ajax_desaprobar_item, name='AJAX Desaprobar items de proyecto'),
    path('restaurarItem/', ajax.ajax_restaurar_item, name='AJAX Restaurar Item de Proyecto'),
    # AJAX Archivos
    path('solicitarSubidaArchivo/', ajax.ajax_obtener_url_de_subida, name='AJAX Obtener URL de Subida'),
    # AJAX Comite
    path('aceptarRevision/', ajax.ajax_aceptar_revision_item, name='AJAX Aceptar revisión de ítem'),
    path('revisarItem/', ajax.ajax_revisar_item, name="AJAX Revisar ítem"),
]

fases/models.py
from typing import List

from django.db import models
from django.db.models import QuerySet
from item.models import Item
from proyecto.models import Proyecto
from .permisos import PermisoFase


class EstadoFase:
    ABIERTO = 'A'
    CERRADO = 'C'


class Fase(models.Model):
    """Representa a una fase que almacena nombre, descripción, proyecto, numero y estado.

    :meth:`Representación JSON <fases.models.Fase.a_dict_json>` de la Fase.

    :var nombre: Nombre de la fase. Tiene una longitud máxima de 50 caracteres.
    :var descripcion: Descripción de la fase. No tiene longitud máxima.
    :var proyecto: Proyecto al que pertenece una fase.
    :var numero: Identifica el número de fase.
    :var estado: Representa el estado de la fase, que puede ser abierto o cerrado.
    :var usado: True si es que hay tipos de item con la fase, False caso contrario.

    """
    ESTADOS_FASE = (
        ('A', "Abierto"),
        ('C', "Cerrado"),
    )
    nombre = models.CharField("Nombre de la fase", max_length=50)
    descripcion = models.TextField("Descripción de la fase")
    proyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE, null=True)
    numero = models.IntegerField("Numero de la fase", default=-1)
    estado = models.CharField("Estado de la fase", max_length=1, choices=ESTADOS_FASE)

    def cerrar(self) -> bool:
        """Cierra una Fase

        :return: Verdadero si se pudo cerrar la fase, Falso caso contrario
        """
        self.estado = EstadoFase.CERRADO
        self.save()
        return True

    @property
    def usado(self) -> bool:
        """Retorna True si la fase se usa en algún tipo de item, caso contrario, Retorna False

        :return: Si es que la fase se usa en algún item.
        :rtype: bool
        """
        return self.tipos_de_item.exists()

    @property
    def tiene_item_para_informe(self):
        """Retorna True si la fase tiene items en desarrollo o pendientes de aprobacion, caso contrario, Retorna False

        :return: Si es que la fase tiene items en desarrollo o pendiente de aprobacion.
        :rtype: bool
        """
        return Item.listar_items_de_fase_queryset(self.id) \
                   .exclude(es_ultimo=False) \
                   .exclude(estado__in=['LB', 'IA', 'DA']).count() > 0

    def esta_cerrado(self) -> bool:
        """Retorna True si la fase esta cerrada, caso contrario, retorna False

        :return: Si es que la fase esta cerrada
        :rtype: bool

        """
        return self.estado == EstadoFase.CERRADO

    def a_dict_json(self) -> dict:
        """Retorna un diccionario en la representación json de la fase.

        La representación JSON es:

        .. code-block:: python

           [{
           "id": ID_DE_FASE,
           "nombre": "NOMBRE_DE_FASE",
           "descripcion": "DESCRIPCION_DE_FASE",
           "proyecto": PROYECTO_ID,
           "numero": NUMERO_DE_FASE,
           "cerrado": TRUE_SI_ESTA_CERRADO_FALSE_SI_ABIERTO,
           "usado": SI_TIENE_TIPOS_DE_ITEM,
           "cerrable": SI_SE_PUEDE_CERRAR,
           }]

        :return: Diccionario de la fase

        """
        from .utils import se_puede_cerrar_fase
        return {
            "id": self.id,
            "nombre": self.nombre,
            "descripcion": self.descripcion,
            "proyecto": self.proyecto_id,
            "numero": self.numero,
            "cerrado": self.esta_cerrado(),
            "usado": self.usado,
            "cerrable": se_puede_cerrar_fase(self),
        }

    @staticmethod
    def listar_fases_proyecto_queryset(proyecto_id: int) -> QuerySet:
        """Retorna la lista de fases de un proyecto como queryset.

        :param proyecto_id: Identificador del Proyecto
        :type proyecto_id: int
        :return: Lista de fases del proyecto
        :rtype: QuerySet<Fase>

        """
        return Fase.objects.filter(proyecto_id=proyecto_id).order_by('numero')

    @staticmethod
    def listar_fases_proyecto_json(proyecto_id) -> List[dict]:
        """Retorna una lista de diccionarios de las fases ordenado por la numeración de la fase
        dentro del proyecto

        Los diccionarios tienen la estructuras de la :meth:`Representación JSON <fases.models.Fase.a_dict_json>` de la
        fase.

        :param proyecto_id: Identificador del Proyecto
        :type proyecto_id: int
        :return: Lista de diccionarios de fases
        :rtype: list

        """
        return [fase.a_dict_json() for fase in Fase.listar_fases_proyecto_queryset(proyecto_id)]

    def __str__(self):
        return "{numero}. {nombre}".format(numero=self.numero, nombre=self.nombre)

    class Meta:
        permissions = [
            # Items
            (PermisoFase.CREAR_ITEM, 'Puede crear items en la fase'),
            (PermisoFase.MODIFICAR_ITEM, 'Puede modificar items en la fase'),
            (PermisoFase.APROBAR_ITEM, 'Puede aprobar items en la fase'),
            (PermisoFase.DESAPROBAR_ITEM, 'Puede desaprobar items en la fase'),
            (PermisoFase.ELIMINAR_ITEM, 'Puede eliminar items de la fase'),
            (PermisoFase.RELACIONAR_ITEM, 'Puede relacionar items en la fase'),
            # Linea Base
            (PermisoFase.CREAR_LINEA_BASE, 'Puede crear lineas base en la fase'),
            (PermisoFase.MODIFICAR_LINEA_BASE, 'Puede modificar los atributos de la linea base'),
            (PermisoFase.ELIMINAR_LINEA_BASE, 'Puede eliminar lineas bases abiertas en la fase'),
            (PermisoFase.CERRAR_LINEA_BASE, 'Puede cerrar lineas bases en la fase'),
            # Solicitud de cambio
            (PermisoFase.SOLICITAR_CAMBIO, 'Puede pedir solicitud de cambio en la fase'),
        ]

templates/pdf_templates/InformeFase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Informe</title>
    <style>
        table, th, td {
            border: 1px solid black;
        }

        th, td {
            text-align: center;
            padding-top: 2px;
        }

        .fecha-creacion {
            float: right;
        }
    </style>
</head>
<body>
<h1 style="float: left">Informe de Fase</h1>

<ul>
    <li><b>Proyecto: </b>{{ fase.proyecto.nombre }}</li>
    <li><b>Nombre de Fase: </b>{{ fase.nombre }}</li>
    <li><b>Numero de Fase: </b>{{ fase.numero }}</li>
</ul>
<br/>


{% if items.count > 0 %}
    <p><b>Items: </b></p>
    <table style="linea_basewidth:100%">
        <tr>
            <th>Código</th>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Estado</th>
        </tr>
        {% for item in items.all %}
            <tr>
                <td>{{ item.codigo }}</td>
                <td>{{ item.nombre }}</td>
                <td>{{ item.descripcion }}</td>
                <td>{{ item.get_estado_display }}</td>
            </tr>
        {% endfor %}
    </table>
{% endif %}
<hr/>
<p class="fecha-creacion">Fecha de generación: {{ fecha }} {{ hora }}</p>
</body>
</html>

templates/pdf_templates/InformeItems.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Informe</title>
    <style>
        table, th, td {
            border: 1px solid black;
        }

        th, td {
            text-align: center;
            padding-top: 2px;
        }

        .fecha-creacion {
            float: right;
        }
    </style>
</head>
<body>
<h1 style="float: left">Informe de Items</h1>

<b>Proyecto: </b>{{ fases.0.proyecto.nombre }}

{% for fase in fases.all %}
    <ul>
        <li><b>Fase: </b>{{ fase.numero }}. {{ fase.nombre }}</li>
        {% if fase.tiene_item_para_informe %}
            {% if items.count > 0 %}
                <table style="linea_basewidth:100%">
                <tr>
                    <th>Código</th>
                    <th>Nombre</th>
                    <th>Descripción</th>
                    <th>Estado</th>
                </tr>
                {% for item in items.all %}
                    {% if item.fase.id == fase.id %}
                        <tr>
                            <td>{{ item.codigo }}</td>
                            <td>{{ item.nombre }}</td>
                            <td>{{ item.descripcion }}</td>
                            <td>{{ item.get_estado_display }}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
                </table>
            {% endif %}
        {% else %}
            <table style="linea_basewidth:100%">
                <tr>
                    <td>Esta fase no tiene items en desarrollo ni pendientes de aprobacion</td>
                </tr>
            </table>
        {% endif %}
    </ul>
    <br/>
{% endfor %}



<hr/>
<p class="fecha-creacion">Fecha de generación: {{ fecha }} {{ hora }}</p>
</body>
</html>

templates/pdf_templates/InformeLineaBase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Informe</title>
    <style>
        table, th, td {
            border: 1px solid black;
        }

        th, td {
            text-align: center;
            padding-top: 2px;
        }

        .fecha-creacion {
            float: right;
        }
    </style>
</head>
<body>
<h1 style="float: left">Informe de Línea Base</h1>

<ul>
    <li><b>Proyecto: </b>{{ linea_base.fase.proyecto.nombre }}</li>
    <li><b>Nombre:</b> {{ linea_base.nombre }}</li>
    <li><b>Descripción:</b> {{ linea_base.descripcion }}</li>
    <li><b>Fase: </b>{{ linea_base.fase.nombre }}</li>
    <li><b>Estado: </b>{{ linea_base.get_estado_display }}</li>
    <li><b>Numero de línea: </b>{{ linea_base.numero }}</li>
    <li><b>Creador: </b>{{ linea_base.creador.first_name }} {{ linea_base.creador.last_name }}
        - {{ linea_base.creador.email }}</li>
</ul>
<br/>


{% if linea_base.items.count > 0 %}
    <p><b>Items: </b></p>
    <table style="width:100%">
        <tr>
            <th>Código</th>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Costo</th>
        </tr>
        {% for item in linea_base.items.all %}
            <tr>
                <td>{{ item.codigo }}</td>
                <td>{{ item.nombre }}</td>
                <td>{{ item.descripcion }}</td>
                <td>{{ item.costo }}</td>
            </tr>
        {% endfor %}
    </table>
{% endif %}
<hr/>
<p class="fecha-creacion">Fecha de generación: {{ fecha }} {{ hora }}</p>
</body>
</html>

templates/pdf_templates/ReporteSolicitud.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Informe</title>
    <style>
        table, th, td {
            border: 1px solid black;
        }

        th, td {
            text-align: center;
            padding-top: 2px;
        }

        .fecha-creacion {
            float: right;
        }
    </style>
</head>
<body>
<h1 style="float: left">Informe de solicitudes de cambio en un proyecto</h1>

<ul>
    <li><b>Proyecto: </b>{{ proyecto.nombre }}</li>
    <li><b>Descripción:</b> {{ proyecto.descripcion }}</li>
    <li><b>Fecha de inicio:</b> {{ inicio }}</li>
    <li><b>Fecha de fin:</b> {{ fin }}</li>
</ul>
<br/>

{% if solicitudes.count > 0 %}
    <p><b>Items: </b></p>
    <table style="width:100%">
        <tr>
            <th>Item</th>
            <th>Usuario</th>
            <th>Motivo</th>
            <th>Fecha de Solicitud</th>
        </tr>
        {% for solicitud in solicitudes %}
            <tr>
                <td>{{ solicitud.item_solicitante.codigo }} - {{ solicitud.item_solicitante.nombre }}</td>
                <td>{{ solicitud.usuario_solicitante.first_name }} {{ solicitud.usuario_solicitante.last_name }}
                    ({{ solicitud.usuario_solicitante.email }})</td>
                <td>{{ solicitud.motivo }}</td>
                <td>{{ solicitud.fecha_solicitud }}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <h1>No hay ninguna solicitud de cambio en este periodo</h1>
{% endif %}

<hr/>
<p class="fecha-creacion">Fecha de generación: {{ fecha }} {{ hora }}</p>
</body>
</html>